server:
  port: 8082
spring:
  application:
    name: storage-aurora
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://192.168.0.50:3306/aurora?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: password
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true